# Generated by Django 4.2.30 on 2026-08-25 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_etl', '0002_individual_schema_etl_columns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLSyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('cursor', models.CharField(blank=True, max_length=255, null=True)),
                ('last_success_cursor', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAIL', 'Failed')], default='IDLE', max_length=16)),
                ('run_started', models.DateTimeField(blank=True, null=True)),
                ('run_finished', models.DateTimeField(blank=True, null=True)),
                ('records_pulled', models.IntegerField(default=0)),
                ('batches_pushed', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('json_ext', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'api_etl_sync_state',
            },
        ),
    ]
